- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  antagAdvantage: 2 # DeltaV - Reduced TC: External Access
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1800 # LostParadise - 30 min
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    socks: LPPClothingUnderSocksNorm
    underwear: LPPBoxer
  underwear: LPPBriefs
  breast: LPPBraAltWhite
  innerClothingSkirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelCargoFilled
  duffelbag: ClothingBackpackDuffelCargoFilled
