- type: job
  id: LPPBlueShieldOfficer
  name: job-name-blueshieldofficer
  description: job-description-blueshieldofficer
  playTimeTracker: JobBlueShieldOfficer
  requirements:
    - !type:CharacterAgeRequirement
      min: 25
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 108000
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 108000
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 72000
  startingGear: LPPBlueShieldOfficerGear
  icon: "JobIconBlueshield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant, MindShieldImplant ]

- type: playTimeTracker
  id: JobBlueShieldOfficer

- type: startingGear
  id: LPPBlueShieldOfficerGear
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitBlueshield
    head: LPPClothingHeadHatBeretBlueshield
    back: LPPClothingBackpackBlueshieldFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: LPPBlueHudGlasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: LPPClothingOuterArmorBlueshield
    neck: LPPClothingNeckCloakBlueshield
    id: LPPBlueShieldOfficerPDA
    ears: ClothingHeadsetAltCommand
    pocket1: LPPBlueshieldlaser
    pocket2: HandheldCrewMonitor
    socks: LPPClothingUnderSocksNorm
    underwear: LPPBoxer
  underwear: LPPBriefs
  breast: LPPBraAltWhite
  satchel: LPPClothingBackpackSatchelBlueshieldFilled
  duffelbag: LPPClothingBackpackDuffelBlueshieldFilled
  storage:
    back:
    - Flash

- type: entity
  id: SpawnBlueShieldOfficer
  parent: SpawnPointJobBase
  name: BlueShieldOfficer
  components:
    - type: SpawnPoint
      job_id: LPPBlueShieldOfficer
    - type: Sprite
      layers:
        - state: green
        - state: ertleader
