- type: job
  id: LPPSecurityEnginer
  name: job-name-security-enginer
  description: job-description-security-enginer
  playTimeTracker: LPPJobSecurityEnginer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 36000
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 72000
  startingGear: LPPSecurityEngineerGear
  icon: "LPPJobIconSecurityEnginer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
#  - Brig
  - Maintenance
  - External
  - Engineering
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: LPPSecurityEngineerGear
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitSecEngineer
    back: LPPClothingBackpackSecurityEngineer
    shoes: LPPClothingShoesBootsJackSecEnginer
    eyes: LPPClothingEyesHudSecEng
    gloves: ClothingHandsGlovesColorYellow
    head: ClothingHeadHatHardhatYellow
    id: LPPSecurityEngineerPDA
    outerClothing: ClothingOuterVestHazard
    ears: LPPClothingHeadsetSecurityEngineer
    belt: LPPClothingMilitaryWebbingSecEng
    socks: LPPClothingUnderSocksNorm
    underwear: LPPBoxer
  underwear: LPPBriefs
  innerClothingSkirt: LPPClothingUniformJumpSkirtSecEngineer
  breast: LPPBraAltWhite
  storage:
    back:
    - SheetSteel10
    - SheetGlass10
    - LPPC4Low
