# - type: job
#   id: SeniorOfficer
#   name: job-name-senior-officer
#   description: job-description-senior-officer
#   playTimeTracker: JobSeniorOfficer
#   requirements:
#     - !type:RoleTimeRequirement
#       role: JobWarden
#       time: 36000 # LPP-RoleTime
#     - !type:RoleTimeRequirement
#       role: JobDetective
#       time: 36000 # LPP-RoleTime
#     - !type:RoleTimeRequirement
#       role: JobSecurityOfficer
#       time: 36000 # LPP-RoleTime
#     - !type:CharacterDepartmentTimeRequirement
#       department: Security
#       time: 108000 # 30 hrs
#   startingGear: SeniorOfficerGear
#   icon: "JobIconSeniorOfficer"
#   supervisors: job-supervisors-hos
#   canBeAntag: false
#   access:
#   - Security
#   - Brig
#   - Maintenance
#   - Service
#   - External
#   special:
#   - !type:AddImplantSpecial
#     implants: [ MindShieldImplant ]

# - type: startingGear
#   id: SeniorOfficerGear
#   equipment:
#     eyes: ClothingEyesGlassesSecurity
#     id: SeniorOfficerPDA
#     ears: ClothingHeadsetSecurity
#     pocket1: WeaponPistolMk58
