name: Check Merge Conflicts

on:
  push:
    branches:
    - master
  pull_request_target:

jobs:
  Label:
    if: github.actor != 'PJBot' && github.actor != 'DeltaV-Bot' && github.actor != 'SimpleStation14' != 'Lost-Paradise-Bot'
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: ike709/actions-label-merge-conflict@9eefdd17e10566023c46d2dc6dc04fcb8ec76142
        with:
          dirtyLabel: "Статус: Конфликт"
          repoToken: "${{ secrets.BOT_TOKEN }}"
          commentOnDirty: "В этом ПР'е есть конфликты, пожалуйста, устраните их, прежде чем мы сможем оценить ваш ПР."
