name: Publish-lostparadise

concurrency:
  group: publish-lostparadise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'

    # - name: Download parts
    #   run: |
    #     git clone ${{ secrets.HUB_SEC_TOKEN }}
    #     mv Secrets/_PrivateResources/_Private Resources/Prototypes/
    #     mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
    #     mv Secrets/_PrivateShared Content.Shared/_PrivateShared
    #     mv Secrets/_PrivateServer Content.Server/_PrivateServer
    #     mv Secrets/_PrivateClient Content.Client/_PrivateClient

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64 --platform win-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Upload build artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: release/*.zip
        compression-level: 0
        retention-days: 0

    - name: Publish version
      run: Tools/publish_github_artifact.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        ARTIFACT_ID: ${{ steps.artifact-upload-step.outputs.artifact-id }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - uses: geekyeggo/delete-artifact@v5
      if: always()
      with:
        name: build
