name: Build & Test Debug Secrets


on:
  push:
    branches: [ master, staging, trying ]
  merge_group:

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'DeltaV-Bot' && github.actor != 'SimpleStation14' && github.actor != 'Lost-Paradise-Bot' && github.repository == 'Lost-Paradise-Project/Lost-Paradise'
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3.6.0

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Download parts
      run: |
        git clone ${{ secrets.HUB_SEC_TOKEN }}
        mv Secrets/_PrivateResources/_Private Resources/Prototypes/
        mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
        mv Secrets/_PrivateShared Content.Shared/_PrivateShared
        mv Secrets/_PrivateServer Content.Server/_PrivateServer
        mv Secrets/_PrivateClient Content.Client/_PrivateClient

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Content.Tests
      run: dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        $env:DOTNET_gcServer=1
        dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed
  ci-success:
    name: Build & Test Debug
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: CI succeeded
      run: exit 0
